spring:
  application:
    name: linkWhiz-backend
  jackson:
    time-zone: UTC
  profiles:
    active: dev
  datasource:
    url: 'jdbc:postgresql://${DB_HOST:localhost}:5432/LinkWhiz'
    username: ${DB_USER:postgres}
    password: ${DB_PASS:123456789}
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  #  sql:
  #    init:
  #      mode: always

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update


server:
  port: ${PORT:8080}

logging:
  level:
    root: info

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

