spring:
  application:
    name: linkWhiz-backend

  datasource:
    url: jdbc:postgresql://${ENV:localhost}:5432/linkWhiz
    username: ${DB_USER:postgres}
    password: ${DB_PASS:123456789}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port: ${PORT:8080}
  servlet:
    context-path: ${BASE_PATH:/api}

logging:
  level:
    root: INFO
