spring:
  application:
    name: linkWhiz-backend
  jackson:
    time-zone: UTC
  profiles:
    active: dev
  datasource:
    url: 'jdbc:postgresql://${DB_HOST:localhost}:5432/LinkWhiz'
    username: ${DB_USER:postgres}
    password: ${DB_PASS:123456789}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port: ${PORT:8080}
  servlet:
    context-path: ${BASE_PATH:/api/v1}

logging:
  level:
    root: INFO

